title: Emma Zimmerman # your name (or website title) here
logo: "/images/GetPersonaPhoto.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bachelor's of Science in Computer Science, minor in Math, and a minor in Computer Engineering from Seattle Pacific University
  <br><br>
  I have experience in Product Support, Cloud Computing, Web Development, Machine Learning, Data Science, Data Structures, and Education 
  <br><br>
  AWS Cloud Practioner Certified
  <br><br>
  Experience in: Python, C++, JavaScript, and R
  <br><br>
  <a href="https://www.linkedin.com/in/emma-zimmerman-profile/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
